version: '3'
services:
  # MYSQL
  db:
    image: mysql:5.7
    restart: always
    container_name: phpadmin_db_1
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/dump:/docker-entrypoint-initdb.d
      - ./.docker/mysql/log:/var/log/mysql
      - ./.docker/mysql/conf:/etc/mysql/conf.d
  
  #PHPMyAdmin
  pma:
    image: 'phpmyadmin/phpmyadmin'
    restart: always 
    environment:
      PMA_HOST: db
    ports:
      - "9001:80"

  # PHP
  phpfpm:
    build: 
      context: .
      dockerfile: ./.docker/php/Dockerfile
    links:
      - db:db
    volumes:
      - ./.docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/log:/var/log/php-fpm
      - ./src:/var/www/html

  # NGINX
  nginx:
    image: nginx:1.15
    ports:
      - "8000:80"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
      - ./.docker/nginx/log:/var/log/nginx
